# Generated by Django 5.2.6 on 2025-10-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDelito',
            fields=[
                ('numero_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('codigo_delito', models.IntegerField(blank=True, null=True)),
                ('tipo_delito', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_delito', models.CharField(blank=True, max_length=255, null=True)),
                ('distrito', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.IntegerField(blank=True, null=True)),
                ('clasificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('calle', models.CharField(blank=True, max_length=255, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
