# Generated by Django 5.2.6 on 2025-10-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_datos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDelitoReal',
            fields=[
                ('cod_form_01', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cod_n', models.CharField(blank=True, max_length=50, null=True)),
                ('gestion', models.IntegerField(blank=True, null=True)),
                ('mes_registro', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_denuncia', models.DateField(blank=True, null=True)),
                ('dias', models.CharField(blank=True, max_length=50, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('municipios', models.CharField(blank=True, max_length=100, null=True)),
                ('macro_distrito', models.CharField(blank=True, max_length=100, null=True)),
                ('zona_del_hecho', models.CharField(blank=True, max_length=255, null=True)),
                ('avenida_calle', models.CharField(blank=True, max_length=255, null=True)),
                ('naturaleza_delito', models.CharField(blank=True, max_length=255, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
